#pragma once
#include "stm32f4xx_hal.h"
#include "FreeRTOS.h"
#include "task.h"

#define WS2812B_GPIO_CLK_ENABLE() __HAL_RCC_GPIOC_CLK_ENABLE()
#define WS2812B_PORT GPIOC
#define WS2812B_PINS GPIO_PIN_0

#define MOCK_SENSOR_USART_GPIO_CLK_ENABLE() __HAL_RCC_GPIOB_CLK_ENABLE()
#define MOCK_SENSOR_USART_GPIO_PIN (GPIO_PIN_10 | GPIO_PIN_11)
#define MOCK_SENSOR_USART_GPIO_ALTERNATE GPIO_AF7_USART3
#define MOCK_SENSOR_USART_CLK_ENABLE() __HAL_RCC_USART3_CLK_ENABLE()
#define MOCK_SENSOR_USART USART3
#define MOCK_SENSOR_USART_BAUDRATE 115200

#define SENSORS_TIME_DELTA 10000   //ms
#define LOWER_SENSORS_DISTANCE 100 //sm
#define UPPER_SENSORS_DISTANCE 100 //sm
#define STAIR_LENGTH 30            //sm
#define STAIRS 2
#define LEDS_ON_STAIR 1
#define LED_RED 128
#define LED_GREEN 0
#define LED_BLUE 255