#pragma once
#include "stm32f1xx_hal.h"
#include "FreeRTOS.h"
#include "task.h"

#define WS2812B_GPIO_CLK_ENABLE() __HAL_RCC_GPIOA_CLK_ENABLE()
#define WS2812B_PORT GPIOA
#define WS2812B_PINS GPIO_PIN_2

#define MOCK_SENSOR_USART_GPIO_CLK_ENABLE() __HAL_RCC_GPIOA_CLK_ENABLE()
#define MOCK_SENSOR_USART_GPIO_PORT GPIOA
#define MOCK_SENSOR_USART_GPIO_TX_PIN GPIO_PIN_9
#define MOCK_SENSOR_USART_GPIO_RX_PIN GPIO_PIN_10
#define MOCK_SENSOR_USART_CLK_ENABLE() __HAL_RCC_USART1_CLK_ENABLE()
#define MOCK_SENSOR_USART USART1
#define MOCK_SENSOR_USART_BAUDRATE 115200
#define SENSORS_VL_XSHUT_GPIO_RCC_Enable __HAL_RCC_GPIOB_CLK_ENABLE
#define SENSORS_VL_XSHUT_GPIO_Port GPIOB
#define SENSORS_VL_XSHUT_Pin GPIO_PIN_0
#define SENSORS_VL_I2C_GPIO_RCC_Enable __HAL_RCC_GPIOB_CLK_ENABLE
#define SENSORS_VL_I2C_GPIO_SCL GPIO_PIN_10
#define SENSORS_VL_I2C_GPIO_SDA GPIO_PIN_11
#define SENSORS_VL_I2C_GPIO_SCL_PORT GPIOB
#define SENSORS_VL_I2C_GPIO_SDA_PORT GPIOB
#define SENSORS_VL_I2C I2C2
#define SENSORS_VL_I2C_RCC __HAL_RCC_I2C2_CLK_ENABLE

#define SENSORS_TIME_DELTA 10000   //ms
#define LOWER_SENSORS_DISTANCE 100 //sm
#define UPPER_SENSORS_DISTANCE 100 //sm
#define STAIR_LENGTH 30            //sm
#define STAIRS 2
#define LEDS_ON_STAIR 1
#define LED_RED 128
#define LED_GREEN 0
#define LED_BLUE 255